<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bolius_langcheck"
 *
 * Auto generated by Extension Builder 2013-12-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Bolius: Language check',
	'description' => 'Adds a spamfilter to the following extensions, to assign spam points based on language
 - comments
',
	'category' => 'plugin',
	'author' => 'Bolius Online',
	'author_email' => 'egi@bolius.dk',
	'author_company' => 'Bolius',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>